# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mecanico_ja_db
spring.datasource.username=root
spring.datasource.password=rootpassword

# Configuração do PostGIS (Dialeto Especial)
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisDialect

# Atualiza o banco automaticamente conforme nossas models
spring.jpa.hibernate.ddl-auto=update

# Exibir SQL no console (útil para desenvolvimento)
spring.jpa.show-sql=true